from datetime import datetime, timezone
from typing import Tuple
from app.models.state import PersonalWishesState

class DocumentGenerator:
    """
    Generates a formal, structured Personal Wishes Document from the confirmed structured state.
    Strictly labels the document as fictional and not legal advice.
    """

    DISCLAIMER_TEXT = (
        "FICTIONAL DRAFT - FOR DEMONSTRATION PURPOSES ONLY - NOT LEGAL ADVICE. "
        "This document is dynamically generated by an automated conversational intake system "
        "and does not constitute binding legal counsel, estate planning advice, or statutory legal instruments."
    )

    @classmethod
    def generate(cls, state: PersonalWishesState) -> Tuple[str, str]:
        """
        Returns a tuple of (markdown_content, html_content).
        """
        markdown = cls._generate_markdown(state)
        html = cls._generate_html(state)
        return markdown, html

    @classmethod
    def _generate_markdown(cls, state: PersonalWishesState) -> str:
        date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
        
        name = state.full_name or "[PENDING: FULL LEGAL NAME]"
        address = state.home_address or "[PENDING: RESIDENTIAL ADDRESS]"
        
        # Scope
        if state.covers_worldwide_assets is True:
            scope_text = "This document and declaration shall govern ALL assets, property, and interests worldwide, wherever situated."
            scope_badge = "Worldwide Assets Included"
        elif state.covers_worldwide_assets is False:
            scope_text = "This document and declaration shall govern solely DOMESTIC assets and property situated within the jurisdiction of residence."
            scope_badge = "Domestic Assets Only"
        else:
            scope_text = "[PENDING: Confirmation of worldwide vs. domestic asset jurisdiction]"
            scope_badge = "Pending Scope"

        # Children
        if state.has_children is True:
            if state.children and len(state.children) > 0:
                children_list = "\n".join([f"  * {child}" for child in state.children])
                children_text = f"I confirm that I have children, identified as follows:\n{children_list}"
            else:
                children_text = "I confirm that I have children. [PENDING: SPECIFIC NAMES OF CHILDREN TO BE RECORDED]"
        elif state.has_children is False:
            children_text = "I declare and confirm that I have no children, whether natural or adopted."
        else:
            children_text = "[PENDING: Declaration regarding children/dependents]"

        # Executor
        if state.executor and (state.executor.name or state.executor.relationship):
            exec_name = state.executor.name or "[PENDING: EXECUTOR NAME]"
            exec_rel = state.executor.relationship or "[PENDING: RELATIONSHIP]"
            executor_text = f"I hereby nominate and appoint **{exec_name}** ({exec_rel}) to serve as the Executor and personal representative of my estate and administrator of these wishes."
        else:
            executor_text = "[PENDING: Appointment of Executor and relationship]"

        # Specific Gifts
        if state.specific_gifts and len(state.specific_gifts) > 0:
            gifts_rows = []
            for idx, gift in enumerate(state.specific_gifts, start=1):
                gifts_rows.append(f"{idx}. **{gift.item}** — to be bequeathed and delivered to **{gift.recipient}**.")
            gifts_text = "\n".join(gifts_rows)
        else:
            gifts_text = "*No specific bequests or individual gifts designated at this time.*"

        # Additional Wishes
        if state.additional_wishes and len(state.additional_wishes) > 0:
            wishes_rows = [f"- {wish}" for wish in state.additional_wishes]
            wishes_text = "\n".join(wishes_rows)
        else:
            wishes_text = "*No additional testamentary or personal instructions recorded.*"

        lines = [
            "# LAST WILL & PERSONAL WISHES DOCUMENT",
            "",
            "> **DISCLAIMER:** " + cls.DISCLAIMER_TEXT,
            "",
            f"**Draft Date:** {date_str}  ",
            f"**Document Status:** {'COMPLETED DRAFT' if state.is_complete() else f'IN PROGRESS ({state.completion_percentage()}% Complete)'}  ",
            f"**Jurisdiction Scope:** {scope_badge}",
            "",
            "---",
            "",
            "### 1. DECLARATION OF PRINCIPAL",
            f"I, **{name}**, currently residing at **{address}**, being of sound mind and disposing memory, declare this instrument to represent my formal expression of personal wishes and testamentary intentions.",
            "",
            "### 2. JURISDICTION & ASSET COVERAGE",
            scope_text,
            "",
            "### 3. FAMILY & DEPENDENTS",
            children_text,
            "",
            "### 4. APPOINTMENT OF EXECUTOR",
            executor_text,
            "In the event that the designated executor is unwilling or unable to serve, an alternate administrator shall be designated in accordance with applicable laws.",
            "",
            "### 5. SPECIFIC GIFTS & BEQUESTS",
            gifts_text,
            "",
            "### 6. ADDITIONAL PERSONAL & TESTAMENTARY WISHES",
            wishes_text,
            "",
            "### 7. EXECUTION & ATTESTATION CLAUSE",
            f"IN WITNESS WHEREOF, I have executed this Personal Wishes Document on this _____ day of _______________, 20___.",
            "",
            "______________________________________  ",
            f"**{name}** (Principal / Testator)  ",
            "",
            "#### WITNESS ATTESTATION",
            "Signed, published, and declared by the above-named Principal in our joint presence, and subscribed by us as witnesses in the presence of the Principal and of each other:",
            "",
            "**Witness 1:**  ",
            "Signature: __________________________  Name: __________________________  Address: __________________________  ",
            "",
            "**Witness 2:**  ",
            "Signature: __________________________  Name: __________________________  Address: __________________________  ",
        ]
        return "\n".join(lines)

    @classmethod
    def _generate_html(cls, state: PersonalWishesState) -> str:
        date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
        name = state.full_name or '<span class="pending-field">[PENDING: Full Legal Name]</span>'
        address = state.home_address or '<span class="pending-field">[PENDING: Residential Address]</span>'

        if state.covers_worldwide_assets is True:
            scope_badge = '<span class="scope-pill scope-worldwide">Worldwide Assets</span>'
            scope_text = "This document and declaration shall govern <strong>ALL</strong> assets, property, and interests worldwide, wherever situated."
        elif state.covers_worldwide_assets is False:
            scope_badge = '<span class="scope-pill scope-domestic">Domestic Assets Only</span>'
            scope_text = "This document and declaration shall govern solely <strong>DOMESTIC</strong> assets and property situated within the jurisdiction of residence."
        else:
            scope_badge = '<span class="scope-pill scope-pending">Pending Scope</span>'
            scope_text = '<span class="pending-field">[PENDING: Confirmation of worldwide vs. domestic asset jurisdiction]</span>'

        if state.has_children is True:
            if state.children and len(state.children) > 0:
                ch_items = "".join([f"<li>{c}</li>" for c in state.children])
                children_text = f"<p>I confirm that I have children, identified as follows:</p><ul class='doc-list'>{ch_items}</ul>"
            else:
                children_text = "<p>I confirm that I have children. <span class='pending-field'>[PENDING: Specific names of children to be recorded]</span></p>"
        elif state.has_children is False:
            children_text = "<p>I declare and confirm that I have no children, whether natural or adopted.</p>"
        else:
            children_text = "<p><span class='pending-field'>[PENDING: Declaration regarding children/dependents]</span></p>"

        if state.executor and (state.executor.name or state.executor.relationship):
            exec_name = state.executor.name or '<span class="pending-field">[Pending Name]</span>'
            exec_rel = state.executor.relationship or '<span class="pending-field">[Pending Relationship]</span>'
            executor_text = f"<p>I hereby nominate and appoint <strong>{exec_name}</strong> (<em>{exec_rel}</em>) to serve as the Executor and personal representative of my estate and administrator of these wishes.</p>"
        else:
            executor_text = "<p><span class='pending-field'>[PENDING: Appointment of Executor and relationship]</span></p>"

        if state.specific_gifts and len(state.specific_gifts) > 0:
            gifts_rows = "".join([
                f"<tr><td>{idx}</td><td><strong>{g.item}</strong></td><td>{g.recipient}</td></tr>"
                for idx, g in enumerate(state.specific_gifts, start=1)
            ])
            gifts_html = f"""
            <table class="doc-table">
                <thead><tr><th>#</th><th>Gift / Item</th><th>Designated Beneficiary</th></tr></thead>
                <tbody>{gifts_rows}</tbody>
            </table>
            """
        else:
            gifts_html = "<p class='doc-empty-note'>No specific bequests or individual gifts designated at this time.</p>"

        if state.additional_wishes and len(state.additional_wishes) > 0:
            wishes_items = "".join([f"<li>{w}</li>" for w in state.additional_wishes])
            wishes_html = f"<ul class='doc-list'>{wishes_items}</ul>"
        else:
            wishes_html = "<p class='doc-empty-note'>No additional testamentary or personal instructions recorded.</p>"

        status_class = "status-complete" if state.is_complete() else "status-incomplete"
        status_text = "READY FOR REVIEW" if state.is_complete() else f"DRAFT IN PROGRESS ({state.completion_percentage()}%)"

        return f"""
        <div class="legal-document">
            <div class="legal-disclaimer-banner">
                <span class="warning-icon">&#9888;</span>
                <span><strong>FICTIONAL DOCUMENT NOTICE:</strong> {cls.DISCLAIMER_TEXT}</span>
            </div>

            <header class="doc-header">
                <div class="doc-meta-top">
                    <span class="doc-date">Date: {date_str}</span>
                    <span class="doc-status-badge {status_class}">{status_text}</span>
                    {scope_badge}
                </div>
                <h1 class="doc-title">PERSONAL WISHES DOCUMENT</h1>
                <p class="doc-subtitle">Testamentary Intentions & Personal Directives</p>
                <hr class="doc-divider"/>
            </header>

            <section class="doc-section">
                <h2>1. Declaration of Principal</h2>
                <p>I, <strong>{name}</strong>, residing at <strong>{address}</strong>, being of sound mind and memory, declare this instrument to represent my formal expression of personal wishes.</p>
            </section>

            <section class="doc-section">
                <h2>2. Jurisdiction & Asset Scope</h2>
                {scope_text}
            </section>

            <section class="doc-section">
                <h2>3. Family & Dependents</h2>
                {children_text}
            </section>

            <section class="doc-section">
                <h2>4. Appointment of Executor</h2>
                {executor_text}
                <p class="doc-subtext">The designated Executor shall have full customary authority to carry out the wishes set forth herein.</p>
            </section>

            <section class="doc-section">
                <h2>5. Specific Gifts & Bequests</h2>
                {gifts_html}
            </section>

            <section class="doc-section">
                <h2>6. Additional Personal Wishes</h2>
                {wishes_html}
            </section>

            <section class="doc-section execution-section">
                <h2>7. Execution & Attestation</h2>
                <p>IN WITNESS WHEREOF, I have executed this Personal Wishes Document on this _____ day of _______________, 20___.</p>
                <div class="signature-line">
                    <div class="sig-box">
                        <div class="sig-stroke"></div>
                        <div class="sig-name">{name} (Principal)</div>
                    </div>
                </div>

                <div class="witness-box">
                    <h3>Witness Attestation</h3>
                    <p class="witness-intro">Subscribed by the witnesses in the presence of the Principal and each other:</p>
                    <div class="witness-grid">
                        <div class="witness-col">
                            <strong>Witness 1</strong>
                            <div class="line">Signature: ______________________</div>
                            <div class="line">Name: ___________________________</div>
                            <div class="line">Address: ________________________</div>
                        </div>
                        <div class="witness-col">
                            <strong>Witness 2</strong>
                            <div class="line">Signature: ______________________</div>
                            <div class="line">Name: ___________________________</div>
                            <div class="line">Address: ________________________</div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        """
